spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: siruang-ng-be
  datasource:
    # url: jdbc:postgresql://localhost:35001/siruangng-dev
    url: jdbc:postgresql://localhost:15001/siruangng-dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update